CREATE TABLE IF NOT EXISTS Quotes (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Text TEXT NOT NULL,
    Author TEXT NULL,
    Tags TEXT NULL,
    CharCount INTEGER GENERATED ALWAYS AS (length(Text)) VIRTUAL,
    WordCount INTEGER GENERATED ALWAYS AS (length(Text) / 5.0) VIRTUAL
);

CREATE INDEX IF NOT EXISTS IX_Quotes_Id ON Quotes(Id);
