name: Publish Stable Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'


permissions:
  contents: write

jobs:
  create-release:
    name: Prepare Velopack Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
  build-release:
    name: Build for ${{ matrix.rid }}
    needs: create-release # Depends on the release placeholder being created.
    runs-on: ${{ matrix.runner_os }}
    strategy:
      matrix:
        include:
          - { runner_os: ubuntu-latest, rid: linux-x64 }
          - { runner_os: windows-latest, rid: win-x64 }
          - { runner_os: macos-latest, rid: osx-x64 }
      fail-fast: false
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with: { fetch-depth: 0 }
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
        dotnet-version: '9.0.x'
    - name: Restore .NET tools
      run: dotnet tool restore
    - name: Get version
      id: minver
      shell: bash
      run: |
        VERSION_OUTPUT=$(dotnet minver --default-pre-release-identifiers preview --verbosity error)
        echo "Discovered version: $VERSION_OUTPUT"
        echo "package_version=$VERSION_OUTPUT" >> $GITHUB_OUTPUT
      env:
        DOTNET_NOLOGO: true
    - name: Build Release for ${{ matrix.rid }}
      run: dotnet run .build/targets.cs release --rid ${{ matrix.rid }} --version ${{ steps.minver.outputs.package_version }}
    - name: Upload Velopack artifacts
      uses: actions/upload-artifact@v4
      with:
        name: typical-${{ matrix.rid }}
        path: dist/release/${{ matrix.rid}}
  publish-release:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    needs: build-release
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with: { global-json-file: global.json }
    - name: Restore .NET tools
      run: dotnet tool restore
    - name: Download all build artifacts
      uses: actions/download-artifact@v4
      with:
        path: typical
        pattern: typical-*
        merge-multiple: true
    - name: Get version
      id: minver
      shell: bash
      run: |
        VERSION_OUTPUT=$(dotnet minver --default-pre-release-identifiers preview --verbosity error)
        echo "Discovered version: $VERSION_OUTPUT"
        echo "package_version=$VERSION_OUTPUT" >> $GITHUB_OUTPUT
      env:
        DOTNET_NOLOGO: true
    - name: Aggregate and Upload Release
      run: dotnet run ./build.cs upload-release --version ${{ steps.get_version.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}